# Travis CI (http://travis-ci.org/) is a continuous integration
# service for open source projects.

language: go

go:
    - 1.3.3
    - tip

matrix:
    fast_finish: true


before_install:
    # Remove installing code.google.com/p/go.tools/cmd/cover from go1.4
    - go get -v code.google.com/p/go.tools/cmd/cover || go get -v golang.org/x/tools/cmd/cover
    - go get -v github.com/mattn/goveralls

install:
    - go get -d -v ./... && go build -v .

script:
    - go test -covermode=count -coverprofile=profile.cov -v .

after_script:
    - $HOME/gopath/bin/goveralls -coverprofile=profile.cov -service=travis-ci
